### ISSUE TITLE
2.9.2 breaks Cocoapods usage

### ISSUE THREAD

**Issue by ghost** [Building42/HTTPParserC#1]
My CI started to report a new error after the weekend. Telegraph have stopped compiling with error:

> no such module 'HTTPParserC'

It worked locally. After investigation, we have discovered that clean install of the dependencies is using 2.9.2 that is different then 2.9.2 tagged before. 

It looks like changes related to SPM support (moving files around) have broken `s.source_files` in the podspec. We are using Cocoapods 1.9 and to reproduce it locally, make sure to clean cache first:
```
pod cache clean HTTPParserC
```

**Comment by Pikuseru** [comment]
We had the same issue, we ended up going back to 2.9.0

https://github.com/Building42/Telegraph/issues/77#issuecomment-593435307

**Comment by ghost** [comment]
To have the dependency in the exactly same state as before I went as far as pointing to the exact commit that was under the tag before.
```
pod 'HTTPParserC', git: 'https://github.com/Building42/HTTPParserC', commit: '1979fe3'
```
https://github.com/Building42/HTTPParserC/commit/1979fe32c6540ad3010741f08bfba4a1d003c908

**Comment by yvbeek** [comment]
Sorry guys, I made some changes to support SwiftPM and tried to keep the version the same to match the `http-parser` library version. I believe I've resolved the issue. Version 2.9.2 should be working again.

Could you guys test it for me?

Thanks!

**Comment by Pikuseru** [comment]
We updated Telegraph to 0.28 and we've not had any problems 😄 Thank you for looking into this @yvbeek
