### ISSUE TITLE
Xcode 14 beta 5 - Redefinition of enumerator error

### ISSUE THREAD

**Issue by jarekdominiak** [Building42/HTTPParserC#3]
Hi, new version of Xcode 14 beta 5 displays errors during compiling, could someone help resolve that issue?
<img width="254" alt="Screenshot 2022-08-21 at 20 33 28" src="https://user-images.githubusercontent.com/79155136/185805726-4678d4f8-7e57-4f7b-b934-5d41fdb794b7.png">

**Comment by yvbeek** [comment]
Hi @jarekdominiak, this library has now moved over to llhttp, because http_parser is no longer being maintained. The issue has been resolved.
